(cl:defpackage wviz_scene_manager-srv
  (:use )
  (:export
   "ADDMARKER"
   "<ADDMARKER-REQUEST>"
   "ADDMARKER-REQUEST"
   "<ADDMARKER-RESPONSE>"
   "ADDMARKER-RESPONSE"
   "REMOVEMARKER"
   "<REMOVEMARKER-REQUEST>"
   "REMOVEMARKER-REQUEST"
   "<REMOVEMARKER-RESPONSE>"
   "REMOVEMARKER-RESPONSE"
  ))

